name: app
description: A new Flutter project.
publish_to: 'none'
version: 3.18.0+18

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  just_audio:
  just_audio_background:
  path_provider:
  shared_preferences:
  get_storage:
#  google_mobile_ads:
  social_share:
  url_launcher:
  flutter_file_downloader:
  flutter_spinkit:
  permission_handler:
  unity_ads_plugin:

#  dio:
#  flutter_downloader:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "asset/image.jpeg"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - asset/
